- name: setup-scala
  # You may pin to the exact commit or the version.
  # uses: olafurpg/setup-scala@a2db88fb5c57396fbc1ff29a4bb0420072a3d6d8
  uses: olafurpg/setup-scala@v10
  with:
    # The Java version to install, a string matching the output format from  `jabba ls-remote`. For example, "adopt@1.8" for the latest AdoptOpenJDK 8 version, "adopt@1.11" for the latest AdoptOpenJDK 11 version, or "graalvm@" for the latest GraalVM version.

    java-version: # optional, default is adopt@1.8
    # The Jabba version to install.
    jabba-version: # optional, default is 0.11.2
